# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'stripeExample' do
#  pod 'react-native-stripe', path: '../node_modules/react-native-stripe'
  pod 'react-native-stripe', path: '../../..'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport'
  ]
end

